model:
  class_path: modelling.models.aes.base.VAE
  init_args:
    config:
      class_path: modelling.models.aes.base.VAEConfig
      init_args:
        d_decoder: 1024
        d_encoder: null
        latent_dim: 256
        kl_weight: 1.0
        temperature: 1.0
        encoder_n_pooling_tokens: 1
        encoder:
          class_path: modelling.models.aes.base.HFBackboneConfig
          init_args:
            model_class_path: transformers.XLSTMModel
            pretrained_model_name_or_path: mistralai/xlstm-base
            config_class_path: transformers.XLSTMConfig
            load_pretrained: false
            config_kwargs:
              trust_remote_code: true
        decoder:
          class_path: modelling.models.aes.base.HFBackboneConfig
          init_args:
            model_class_path: transformers.XLSTMModel
            pretrained_model_name_or_path: mistralai/xlstm-base
            config_class_path: transformers.XLSTMConfig
            load_pretrained: false
            config_kwargs:
              trust_remote_code: true

